### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by tripped144** [Iniquitatis/sd-webui-temporal#3]
I get a NotImplementedError when trying to run it. It starts running and finishes one image then errors. This is the error - 

Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "E:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "E:\AI\stable-diffusion-webui\modules\img2img.py", line 240, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 780, in run
        processed = script.run(p, *script_args)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\scripts\main.py", line 324, in run
        return self._process(p, self._ui.recombine(*args))
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\scripts\main.py", line 385, in _process
        project.save(project.path)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\project.py", line 57, in save
        super().save(dir / "project")
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\meta\serializable.py", line 99, in save
        self.write(ar)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\meta\serializable.py", line 81, in write
        ar[key].write(getattr(self, key))
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 54, in write
        _serializers[type_name].write(obj, self)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\meta\serializable.py", line 47, in write
        obj.write(ar)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\meta\serializable.py", line 81, in write
        ar[key].write(getattr(self, key))
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 54, in write
        _serializers[type_name].write(obj, self)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 269, in write
        ar.make_child().write(value)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 54, in write
        _serializers[type_name].write(obj, self)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 156, in write
        cls._write_value(obj, ar, key)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 164, in _write_value
        ar[key].write(get_property_by_path(obj, key))
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-temporal\temporal\serialization.py", line 56, in write
        raise NotImplementedError
    NotImplementedError

---

**Comment by Iniquitatis** [comment]
Thanks for the report. Forgot to check it with the ControlNet extension installed. Will fix soon.

**Comment by Iniquitatis** [comment]
Fixed. Thanks again!
